### ISSUE TITLE
依赖里面一定要加上安卓的吗？

### ISSUE THREAD

**Issue by z201** [cping/LGame#22]
我只是想跑跑demo，项目依赖有安卓的。有没有办法区分调。

**Comment by cping** [comment]
不必，可以单独导入，桌面版搞demo有loon-core-0.5.jar和loon-javase-0.5.jar(或者loon-lwjgl3-0.5.jar看您希望用lwjgl的哪个版本)还有相关的lwjgl依赖jar就行了，您可以自行建立工程直接导入相关jar或源代码，不必按照的的设置去做。或者您用loon-gradle-template的gradle示例直接删其它的依赖，只留下javase或者lwjgl3的相关配置就行。我以后会做成可视化ui直接提供环境设置与导出功能，目前正在修正核心代码和开发C#与C++版，这部分就耽误了，需要您稍微手动设置下。
